workflows:
  build:
    name: build
    scripts:
      - ./gradlew ios:createIPA
    instance_type: mac_mini
    environment:
      xcode: 13.2
      java: 17.0.1
    cache:
      cache_paths:
        - $HOME/.gradle/caches
    artifacts:
      - ios/build/robovm/*.ipa
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true